# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000
    context-path: /zhiyi

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    #resources:
    #    static-locations: classpath:/static/
    # THYMELEAF
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        # Thymeleaf缓存在开发过程中,把缓存关闭,devtools可以实现页面热部署,用于支持页面修改后重新发布到spring-boot内嵌的tomcat中去
        cache: false
        # thymeleaf模板对没有结束符的HTML5标签解析出错的解决办法
        mode: LEGACYHTML5
    # redis
    redis:
        database: 0 # Redis数据库索引（默认为0）
        host: 127.0.0.1
        port: 6379
        password:       # 密码（默认为空）
        timeout: 0  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    # rabbitmq
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: admin
        password: adminpwd

# Mybatis配置
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.idou.modules.sysBs.entity
    check-config-location: true
    config-location: classpath:mybatis.xml

idou:
    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: zhiyi_secret
        # token有效时长，7天，单位秒
        expire: 604800
        header: token

img:
    location: F:/FTPFinCloud/images/
    nginxLocation: http://localhost:8088