spring:
    datasource:
        url: jdbc:mysql://62.234.117.116:3306/zhiyi?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Andysi7521$
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

img:
    location: /usr/FTPFinCloud/
    nginxLocation: http://62.234.117.116:8088